apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teslamate
  name: teslamate
  namespace: teslamate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teslamate
  template:
    metadata:
      labels:
        app: teslamate
    spec:
      volumes:
        - name: teslamate-storage
          persistentVolumeClaim:
            claimName: teslamate-pvc
        - name: teslamate-grafana-storage
          persistentVolumeClaim:
            claimName: teslamate-grafana-pvc
      containers:
        - image: teslamate/teslamate
          name: teslamate
          env:
            - name: DATABASE_USER
              value: teslamate
            - name: DATABASE_NAME
              value: teslamate
            - name: DATABASE_HOST
              value: postgres-postgresql-primary.postgres.svc.cluster.local
            - name: MQTT_HOST
              value: mosquitto.mosquitto.svc.cluster.local
            - name: TZ
              value: Europe/Berlin
          envFrom:
            - secretRef:
                name: teslamate-pass
          volumeMounts:
            - mountPath: "/opt/app/import"
              name: teslamate-storage
          ports:
            - containerPort: 4000
              protocol: TCP
        - image: teslamate/grafana
          name: grafana
          env:
            - name: DATABASE_USER
              value: teslamate
            - name: DATABASE_NAME
              value: teslamate
            - name: DATABASE_HOST
              value: postgres-postgresql-primary.postgres.svc.cluster.local
            - name: GF_SERVER_DOMAIN
              value: "grafana.teslamate.leibold.tech"
            - name: GF_SERVER_ROOT_URL
              value: "https://grafana.teslamate.leibold.tech"
            - name: GF_DATABASE_type
              value: postgres
            - name: GF_DATABASE_USER
              value: grafana
            - name: GF_DATABASE_HOST
              value: postgres-postgresql-primary.postgres.svc.cluster.local
            - name: GF_DATABASE_NAME
              value: grafana
          envFrom:
            - secretRef:
                name: grafana-pass
          ports:
            - containerPort: 3000
              protocol: TCP
          # volumeMounts:
          #   - mountPath: "/var/lib/grafana"
          #     name: teslamate-grafana-storage
