apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teslamate-pass
  namespace: teslamate
spec:
  encryptedData:
    DATABASE_PASS: AgAjnw4wqtm0t+94kmpUYcvQT475XAt5A+S1koCB0LaF0vt8RwUfmxnTxwe9Ohn6TesXKGzxH77fVqXB51CihGXXdaio9JcDjhlK5fWf9M4VRFJyW4z0YTVUh9oMaU2nA9GSGx2tsErqE24f27tQaff7d46tfOULa9pb+Bo4FvgjfIetYgVzZXQu+lTl/nG9mH/LrYV72qs+SJpK2WnBsL6+sJO+sDA/H18Me1HVddcEWZ+oICNW4ELMBl6dPDTzyooTP3XodPZR61+sPpqHL2je3RuB6dN6mfxAj4SWDAsOF3m4ntlU79Ia2ZcIk1pxdxYZ8VQW7pNV6M+YF04zNtkKCALzOX3v+z+Kzbd/zIa3eN2CVmtn97Gu78kRtkO/ZdcJzasU9+hjUKvwkM80Qmaw/WmCtOW8qxQxiOVOLodg1hliQpKvUbd71txlgwOh4Z6Ive3NbEFUtZU0qfNtc+1XLoRPMbPoAJjg7ya1chTaO4gIfGjvy0LNxLvLRaBaofVduSIZqjkSrSqYl8PdzHNpeOmTZJLZltYKmElAan+NQxsgz47wBvj8/ivW9GWyfBE1s3hib/Yt0StOpU0m8wAxYPz6nEhxHczp+0GZmjGu0EQKHLHzcKoNBqwfoR+pnXnGvH8xTkG5iR4dGvepcSDJ20Mc71tI1ufHWFW4cSiWzkvvqbJ38zP/azXM/1VbQkCTy4F1w36bjuBX1/atncs=
    ENCRYPTION_KEY: AgA0u+dEvqLUKA9T65dsBCAhRtQMiG2iCWyolr9RYQouVpA7A6U8I2LNcLHJKy/qz8nUEA4EAnRIimA8pLmux2BpOi8SyRS5qnNF8/1joXRluHRxzcZKAXkujEIrKqSTg3t670h9bdTOyWW8wl8FjHDscw+5qKGMXkfcCPw5p6yNeOsAHVjIRypxDRJclEnzRkirTSNi+dQ8EeGxIgAWMf+lGJPqMCYn3yiZNCTLHifLRQZXa0q2rYCeFCx8IetNJWh3AqdsFN1BgEy4aLFMcB3hmdSTOPUEhpn03oDVKgGEL552Uo9GVRfKL3mvBE+ysR2sR5s7fHCWv/dOSw8NrLoEJncV6YUIZuE9Ggnr6tp8MmOd/0PpI3RdMJH2cS6UnbM/7rMINKmYiPzpuHxTB0Nc3E8CvwlccDFLof7Qaif2W5BU5+ZVAthvz5rZPFivGovVHB0YNg9YNMNKmP3i/SbdV2FdHqXvwlQFhuXprAERNmMNDGA9YmYAq/0xg8t2/xeJQoXgL7uMp9wp+8rtjCXRZomdq0rq+DB1LTA0W0h5gBGPoHD6TkYSyYhULHj4LXBKGRIZfTBFk+YaWS4UG3ZmwRW4CzfdGR8QkKbvvHqnfyna2g/2dUfM0p9ni3QNUnVyQTni5BuXSGA16Oj8egmwTJkfFJAowiR1jxfUqexRAcvFphm4S8Q4F3sQxa+vSr0GOUoliZKUMIjOS1FwO0rLPCV+RQ==
  template:
    metadata:
      creationTimestamp: null
      name: teslamate-pass
      namespace: teslamate
    type: Opaque
