apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-pvc
  namespace: teslamate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-grafana-pvc
  namespace: teslamate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ssd
